services:
  db:
    image: "mysql:8.0-debian"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: database

  web:
    image: "php:8.1-apache"
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password


