apiVersion: v1
data:
  MYSQL_DATABASE: ZGF0YWJhc2U=
  MYSQL_HOST: bXlzcWwtc2VydmljZTozMzA2
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: dXNlcg==
kind: Secret
metadata:
  name: mysql-secret
