apiVersion: v1
data:
  MYSQL_DATABASE: {{ .Values.mysqlDatabase | b64enc }}
  MYSQL_HOST: {{ .Values.mysqlHost | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysqlPassword | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysqlUser | b64enc }}
kind: Secret
metadata:
  name: mysql-secret
