apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-deploy
  name: php-service
spec:
  ports:
  - port: {{ .Values.phpServicePort }}
    protocol: TCP
    targetPort: 80
  selector:
    app: php-deploy
  type: ClusterIP
status:
  loadBalancer: {}
